// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repleet.Data;

#nullable disable

namespace Repleet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250415223959_UserRolesAndRefreshTokens")]
    partial class UserRolesAndRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Repleet.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProblemSetId")
                        .HasColumnType("integer");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProblemSetId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Repleet.Models.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<int>("CurrentSkill")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProblemSetId")
                        .HasColumnType("integer");

                    b.HasKey("CategoryId");

                    b.HasIndex("ProblemSetId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Repleet.Models.Entities.Problem", b =>
                {
                    b.Property<int>("ProblemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProblemId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProblemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("Repleet.Models.Entities.ProblemSet", b =>
                {
                    b.Property<int>("ProblemSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProblemSetId"));

                    b.HasKey("ProblemSetId");

                    b.ToTable("ProblemSets");
                });

            modelBuilder.Entity("Repleet.Models.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Repleet.Models.Entities.ProblemSet", "ProblemSet")
                        .WithOne()
                        .HasForeignKey("Repleet.Models.Entities.ApplicationUser", "ProblemSetId");

                    b.Navigation("ProblemSet");
                });

            modelBuilder.Entity("Repleet.Models.Entities.Category", b =>
                {
                    b.HasOne("Repleet.Models.Entities.ProblemSet", null)
                        .WithMany("Categories")
                        .HasForeignKey("ProblemSetId");
                });

            modelBuilder.Entity("Repleet.Models.Entities.Problem", b =>
                {
                    b.HasOne("Repleet.Models.Entities.Category", "Category")
                        .WithMany("Problems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Repleet.Models.Entities.Category", b =>
                {
                    b.Navigation("Problems");
                });

            modelBuilder.Entity("Repleet.Models.Entities.ProblemSet", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
